CREATE PARTITION FUNCTION pfInvoiceDate(DATETIME)
AS RANGE RIGHT FOR VALUES ('2023-01-01', '2024-01-01', '2025-01-01', '2026-01-01')
GO

CREATE PARTITION SCHEME psInvoiceDate
AS PARTITION pfInvoiceDate TO ([PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY])
GO

CREATE UNIQUE NONCLUSTERED INDEX IX_Invoice_Clustered
ON Invoice (id, orderAt)
ON psInvoiceDate(orderAt);
GO
