CREATE OR ALTER PROCEDURE sp_CompleteOrder
CREATE OR ALTER PROCEDURE sp_SubmitOrder
CREATE OR ALTER PROCEDURE sp_CancelOrder
CREATE OR ALTER PROCEDURE sp_AcceptOrder
CREATE OR ALTER PROCEDURE sp_IssueInvoice
