name: Lint Commit Messages

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install commitlint
        run: |
          npm install --save-dev @commitlint/{config-conventional,cli}

      - name: Check commit messages
        run: npx commitlint --from=HEAD~1 --to=HEAD
