name: Check commit message

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check commit messages
        run: |
          commits=$(git log --format=%H -n 10) # Lấy hash commit
          for commit in $commits; do
            message=$(git log --format=%s -n 1 $commit)
            if [[ ! "$message" =~ ^[a-z]+\([a-z]+\):\ .+ ]]; then
              echo "Commit message does not follow convention: $message"
              echo "Removing invalid commit..."
              git reset --hard $commit^ # Lùi lại trước commit vi phạm
              exit 1
            fi
          done
